### ISSUE TITLE
Cannot run examples

### ISSUE THREAD

**Issue by zimmicz** [PANmedia/raptor-example#1]
Getting Parse error: syntax error, unexpected '[' in /home/michal/www/raptor-example/classes/Raptor/Example.php on line 16 Call Stack: 0.0194 641488 1. {main}() /home/michal/www/raptor-example/examples/color-menu/example.php:0 0.0195 697200 2. include('/home/michal/www/raptor-example/include.php') /home/michal/www/raptor-example/examples/color-menu/example.php:2 on running any example.
PHP 5.3

**Comment by Petah** [comment]
Hi, the examples use the short array syntax, which require at least PHP 5.4
